### ISSUE TITLE
Timing events associated with Loan/Bond

### ISSUE THREAD

**Issue by evalevelt** [EconomicSL/stress#3] opened 2016-12-19 14:21 UTC
Currently all cashflows associated with a loan/bond occur at the end of the simulation timestep. For my purposes it would be very useful to change this. Is that possible?

**Comment by rafabap** [comment] 2016-12-21 12:26
I think I've found the solution.

All contracts at the moment inherit from 'MasonScheduledContracts'. These implement two functionalities:

- `scheduleEvent` obtains the next Obligation from the contract and 'schedules it', which means it's put in the Mason schedule together with a timestamp, so that, when the simulation time equals the timestamp, Mason calls the contract's `step` method

- `step` is the method which actually enforces the obligation. It sends the obligation to the relevant agents, obtains a response, sends the response to the contract (the bond or loan) and therefore the contract gets a chance to schedule the next obligation.


Now, the problem is that, sometimes, we don't want the contract to schedule the obligation for some time in the future; we want it to enforce it right now. This can be done by calling the contract's `step` method directly. 

The final problem to solve is the case where the contract has scheduled an obligation which we want to enforce right now. Say a bond has scheduled a payment obligation for time A, but we want to do it right now. Someone calls `bond.step()`, which deals with the payment obligation, and handles the response, which involves scheduling a coupon obligation for time B. The problem is, we have not deleted time A from the schedule!! So when we reach time A, Mason thinks there is a scheduled event and therefore calls `bond.step()`, which now has a coupon payment stored as its next obligation, and therefore, the coupon payment is made at time A, rather than at time B.

I'll do some fixing to make sure the two behaviours (the scheduled one and the direct calling of `step`) do not get in each other's way.

**Comment by evalevelt** [comment] 2016-12-28 11:04
this worked very well! leaving it open for the "final problem" bit you address

**Comment by rafabap** [comment] 2016-12-28 11:17
I think this would be best addressed by issue #7 so I'll close this one!

**Closed by rafabap** 2016-12-28 11:17 UTC
